---
resources:
  - type: package
    name: httpd
    action: install
  - type: service
    name: httpd
    action: 
      - enable
      - start
  - type: template
    name: /var/www/html/index.html
    source: index.html.erb
  - type: kernel_module
    name: cramfs
    action: 
      - blacklist
      - disable
      - unload
  
